### ISSUE TITLE
Unable to run caou in Windows

### ISSUE THREAD

**Issue by sebi5361** [corollari/caoutchouc#7]
I can successfully run `caou a.md` in `WSL` as it generates the `a.cautex` file with `latex` instructions in it.

But I am unable to run it in `Windows 10`...
I installed caou in `Windows` this way:
```shell
git clone git@github.com:corollari/caoutchouc.git
cd caoutchouc
npm install
npm link
caou a.md
```
as installing it using `npm install -g caou` resulted in `caou` starting to download `pandoc` but never finishing...
Unfortunately this is what I get when running `caou test.md` in `Windows`:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 20.10)
entering extended mode
(a.cautex
LaTeX2e <2020-10-01> patch level 1
L3 programming layer <2020-10-05> xparse <2020-03-03>)
*
```
Can you explain me how to run `caou` successfully in `Windows`?
Thank you.

**Comment by corollari** [comment]
I see, I've never run caou on windows myself so this is uncharted territory.

Looking at the output that you got it seems that after you ran the locally-installed `caou` the intermediate .cautex file was generated properly but the latex compiler found some problem with it, could you send me `a.cautex` to take a look?

**Comment by sebi5361** [comment]
Actually my `a.cautex` file is empty, so maybe it was not generated that properly?!
`a.md` currently contains `# Caoutchouc` only.

**Comment by sebi5361** [comment]
Any thoughts why my `a.cautex` file is rendered empty under Windows?
